name : 'Test Workflow'
run-name: ${{  github.actor }} is learning the Github Actions

on :
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: checkout
        uses: actions/checkout@v1
        
      - name: build with maven
        run: mvn clean install -Dmaven.test.skip=true
        
      - name: user name
        run: USER_NAME
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrests.DOCKER_PASSWORD }}
          
      - name: docker build and push docker image
        uses: docker/push-action@v1
        with:
          push: true
          tags: user/app:v1.0
